name: Run action

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: echo "im running"
    
